# Generated by Django 5.0 on 2023-12-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setup', '0002_appsetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='app_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_setup.appsetup'),
        ),
    ]
