# Generated by Django 5.0 on 2023-12-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setup', '0004_alter_appsetup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
