# Generated by Django 5.0 on 2023-12-11 13:58

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setup', '0005_appsetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.model_validators.validate_png]),
        ),
    ]
