# Generated by Django 5.0 on 2023-12-11 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_setup', '0006_alter_appsetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='app_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='app_setup.appsetup'),
        ),
    ]
